name: Bug Report
description: Report a bug with the Calculator
title: "[Calculator Bug]: "
labels: ["bug", "calculator"]
body:
  - type: checkboxes
    attributes:
      label: Before submitting, I have
      description: Please ensure you have done all the below things before you submit.
      options:
        - label: Made sure this is actual unintended behaviour.
          required: true
        - label: Double-checked the [Info Page](https://azurlane.mrlar.dev/calculator/info) for potential misunderstandings.
          required: true
        - label: "If this is gameplay/calculation related: Ensured the formula/assumptions/etc. are actually incorrect (provide proof!)."
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the bug you are experiencing.
      placeholder: I attempted...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide the steps you did to trigger this bug.
      placeholder: I did...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Provide information about what you expected to happen.
      placeholder: I expected...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Provide any additional context or words you would like to lose about the bug here.
      placeholder: I...
    validations:
      required: false
