name: Suggestion/Feature Request
description: Suggest a new feature or an addition to an existing feature for the Calculator.
title: "[Calculator Feature req.]: "
labels: ["feature request", "calculator"]
body:
  - type: checkboxes
    attributes:
      label: Before submitting, I have
      description: Please ensure you have done all the below things before you submit.
      options:
        - label: Double-checked existing Issues for a similar feature (including closed ones).
          required: true
        - label: Double-checked the feature does not exist already with either same or slightly different functionality.
          required: true
        - label: Double-checked the feature has not been rejected before.
          required: true
        - label: Ensured the feature makes sense given the context of the game
          required: true
  - type: textarea
    attributes:
      label: Describe what you would like us to add
      description: Provide a clear and concise description of your suggestion.
      placeholder: I would like...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Provide any additional context or words you would like to lose about your suggestion here here.
      placeholder: I...
    validations:
      required: false
